### ISSUE TITLE
`getCommit` and `getRef` missing?

### ISSUE THREAD

**Issue by Falke-Design** [rvagg/ghrepos#6]
Hi,

in the README you provide the functions `getCommit` and `getRef` but I can't find it in the code.

**Comment by ralphtheninja** [comment]
They are created here:

https://github.com/rvagg/ghrepos/blob/e5ff8fded0fb421d4cc0610c1f84d5cc242c0dc0/ghrepos.js#L40-L73

**Comment by Falke-Design** [comment]
Thank you for the quick response! 
Then I need to check again why it is not working, I thought because of the missing functions 😄
